language: php
sudo: false
php:
  - 8.0

branches:
  only:
    - master

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction

stages:
  - test
  - 8.0 test with prefer-lowest

script:
  - composer test

jobs:
  fast_finish: true
  include:
    - stage: 8.0 test with prefer-lowest
      install:
        - travis_retry composer update --no-interaction --prefer-lowest
      php: 8.0
      script:
        - composer test
